#!/bin/sh
# Generated by vim-plug
# Sat 14 Jan 2017 03:30:43 PM PST

nvim -c 'let g:plug_shallow = 0 | PlugUpdate | qa'

PLUG_HOME=~/.config/nvim/plugged

cd $PLUG_HOME/ListToggle/ && git reset --hard b9941f2
cd $PLUG_HOME/Vim-Jinja2-Syntax/ && git reset --hard db595ff
cd $PLUG_HOME/base16-vim/ && git reset --hard de0afc2
cd $PLUG_HOME/ctrlp.vim/ && git reset --hard 7fa89fe
cd $PLUG_HOME/deoplete-flow/ && git reset --hard cd3604c
cd $PLUG_HOME/deoplete-go/ && git reset --hard 3762a44
cd $PLUG_HOME/deoplete-jedi/ && git reset --hard cdbe090
cd $PLUG_HOME/deoplete-ternjs/ && git reset --hard b0bf130
cd $PLUG_HOME/deoplete.nvim/ && git reset --hard 5afce19
cd $PLUG_HOME/hive.vim/ && git reset --hard 5015f9d
cd $PLUG_HOME/neomake/ && git reset --hard 1676be4
cd $PLUG_HOME/nerdtree/ && git reset --hard 2817010
cd $PLUG_HOME/python-mode/ && git reset --hard 2f850dc
cd $PLUG_HOME/swift.vim/ && git reset --hard 080a5cd
cd $PLUG_HOME/tagbar/ && git reset --hard 53e9cb0
cd $PLUG_HOME/vcl-vim-plugin/ && git reset --hard ab58e19
cd $PLUG_HOME/vim-airline-themes/ && git reset --hard 2a97d9e
cd $PLUG_HOME/vim-commentary/ && git reset --hard 73e0d9a
cd $PLUG_HOME/vim-ctrlspace/ && git reset --hard f7987e4
cd $PLUG_HOME/vim-fugitive/ && git reset --hard b754bc2
cd $PLUG_HOME/vim-go/ && git reset --hard 3eb57ac
cd $PLUG_HOME/vim-grepper/ && git reset --hard aba2253
cd $PLUG_HOME/vim-husk/ && git reset --hard ad89559
cd $PLUG_HOME/vim-javascript/ && git reset --hard 96a5b5e
cd $PLUG_HOME/vim-jsbeautify/ && git reset --hard caffda6
cd $PLUG_HOME/vim-json/ && git reset --hard f5e3181
cd $PLUG_HOME/vim-jsx/ && git reset --hard eb656ed
cd $PLUG_HOME/vim-mustache-handlebars/ && git reset --hard d1c983f
cd $PLUG_HOME/vim-scala/ && git reset --hard a6a350f
cd $PLUG_HOME/vim-sensible/ && git reset --hard 4b75359

